### ISSUE TITLE
This mod does not work with 1.21 in the curseforge app

### ISSUE THREAD

**Issue by Windssoul1995** [MelanX/ToolSwap#56] opened 2024-08-27 23:49 UTC
### Minecraft version

1.21.x

### ToolSwap version

1.21-6.00

### NeoForge version

forge-51.0.33

### The latest.log file

N/A

### Issue description

the app will not recognize that the mod will work with anything aside from 1.16.2 through 1.16.5.

**Comment by MelanX** [comment] 2024-08-28 03:22
Which app? You should have provided a log file. Or at least a screenshot. Anything where I get any more info.

**Comment by Windssoul1995** [comment] 2024-08-28 07:17
Through forge. It only works through forge for Minecraft versions 1.16.2-1.16.5. There is no log file because it won’t work with 1.20 it doesn’t even give the option to try.Sent from my iPhoneOn Aug 27, 2024, at 10:22 PM, MelanX ***@***.***> wrote:﻿
Which app? You should have provided a log file.

**Comment by MelanX** [comment] 2024-08-28 07:21
Ahh, the problem is that you use Forge, not NeoForge, I guess. At least if 1.21 is your version. Now, you said something about 1.20. Maybe you downloaded a 1.16 version? I have no idea with no exact info about everything you use exactly.

**Comment by MelanX** [comment] 2024-08-28 16:40
Yes, I checked it now. There is no NeoForge 51.0.33. If you use Forge 51.0.33 (which is 1.21, correct), you're not able to find Automatic Tool Swap using the launcher (since it's not Forge anymore).
Since this doesn't exist and you're using the wrong mod launcher, I'm closing this issue.

**Closed as not planned by MelanX** 2024-08-28 16:40 UTC
Labels: bug, needs more info
